# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0.xci
# IP: The module: 'MICRO_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MICRO_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MICRO_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0.xci
# IP: The module: 'MICRO_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MICRO_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alireza/kos/micro.srcs/sources_1/bd/MICRO/ip/MICRO_ilmb_v10_0/MICRO_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MICRO_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
